apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "this.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "this.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        actorSystemName: {{ include "this.fullname" . }}
        {{- include "this.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.commandConfig }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          envFrom:
            - secretRef:
                name: application-insights
            - secretRef:
                name: postgres
            - secretRef:
                name: contracts-storage
            - configMapRef:
                name: jwt
            - secretRef:
                name: uservice-party-management
            - secretRef:
                name: event-secrets
            - configMapRef:
                name: {{ include "this.fullname" . }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ACCEPTED_AUDIENCES
              valueFrom:
                configMapKeyRef:
                  name: jwt
                  key: JWT_TOKEN_AUDIENCE
            - name: WELL_KNOWN_URLS
              valueFrom:
                configMapKeyRef:
                  name: jwt
                  key: WELL_KNOWN_URL
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8088
              protocol: TCP
            - name: monitoring
              containerPort: 9095
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: management
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 90
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 90
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
