image:
  repository: selcpacr.azurecr.io/pdndinteropuservicepartymanagement
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: v0.1.3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_OPTS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
